### ISSUE TITLE
Allow component reference to have no attributes except id

### ISSUE THREAD

**Issue by jdmarch** [enthought/enaml#55]
This naive user would expect to be able to code something like this:

```
Form:
    Label:
        text = 'foo'
    MyComponent:
        id: my_id
```

However the 'id' line is not sufficient to establish a body for MyComponent, so it is actually necessary to include a 'pass' line after the 'id'.

Why would one want to pre-define a component so thoroughly that there remains nothing else to be defined in line? 

For reusability, to avoid code repetition.
